### ISSUE TITLE
老师，出现这个问题怎么解决？

### ISSUE THREAD

**Issue by nigor-peter** [OpenHUTB/.github#1]
![e2265b0ff858d4c2d48dcbbf1532fc50](https://github.com/user-attachments/assets/6d157f30-44b9-457f-8d81-59eb4f8b8202)
[](url)

**Comment by donghaiwang** [comment]
后面的提示有操作方法，需要配置自己github的邮箱和用户名。

另外提问在另一个仓库的Issues页面： https://github.com/OpenHUTB/.github/issues/1
